### ISSUE TITLE
[question] error when applying the last chunk

### ISSUE THREAD

**Issue by bassamsdata** [simonsaysenjoy/map_rayshade#1]
thank you very much for sharing this code here on GitHub.

I really appreciate your efforts, and I have just one question regarding this code, I'm trying to apply your code, however, I got an error when I execute the last chunk, I'm not sure why. I tried multiple things but didn't succeed, so I said if I could ask you if you encountered something similar.

this is the error:
```r
[1] "Start rendering:"
[1] "2023-02-08 22:21:10 GMT"
Error in file(filename, "w") : cannot open the connection
In addition: Warning messages:
1: In as.POSIXlt.POSIXct(x, tz) : unknown timezone '
'
2: In file(filename, "w") :
  cannot open file '/var/folders/gt/p3pqh3sj21zgctc0fnsfjzvm0000gn/T//RtmpxMgloQ/images/tmp_aut_states_col_1600m.obj': No such file or directory
```

when executing this chunk:
```r
{
  start_time <- Sys.time()
  print("Start rendering:")
  print(start_time, "\n")
  Sys.sleep(2)
  render_highquality(
    filename = paste0("images/", img_name, "_hdr", ".png"),
    samples=256,
    parallel = TRUE,
    light = FALSE,
    interactive = FALSE,
    environment_light="./hdr/phalzer_forest_01_4k.hdr",
    intensity_env = 1.5,
    rotate_env = 270,
    cache_filename = paste0("images/", "tmp_", img_name),
    width = round(3000 * wr),
    height = round(3000 * hr)
  )
  end_time <- Sys.time()
  diff <- end_time - start_time
  print("...Done.")
  print(diff)
}

```

thank you again

**Comment by simonsaysenjoy** [comment]
This does not occur for me.
1) the warning regarding the timezone might come from your system settings. You could comment out delete all parts which return the time. They are only for you to check but not necessary for the function.
2) regarding the filename error - it appears to not find your temporary object file which is created while rendering. If you rerun the code delete all files with an affix "tmp_" (in a bash based terminal  run `rm tmp_*` in the folder). And then run again. 
It appears to be an issue with your local file/folder structure.

In case this doesnt work - let me know. 
Cheers

**Comment by simonsaysenjoy** [comment]
@bassamsdata I hope your issue was solved. I close this quesiton for now - in case it did not get resolved. Please open it again.
